### PR TITLE
Monodepth2 fix getmodel

### PR DESCRIPTION
**Pull request by KuangHaofei**
Fixed get_model bugs while using pretrained mono+stereo weights.

### CODE REVIEW

**Review by bryanyzhu — CHANGES_REQUESTED** [review]
Please change the names in `model_zoo.py` and also the names in tutorials and model zoo page.

**Comment by mli** [comment]
Job PR-1440-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1440/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by KuangHaofei** [comment]
> Please change the names in `model_zoo.py` and also the names in tutorials and model zoo page.

Fixed, thanks for your reminder.

**Comment by mli** [comment]
Job PR-1440-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1440/2/index.html 
Code coverage of this PR:  vs. Master:

**Review by bryanyzhu — APPROVED** [review]

**Pull request merged**
