### PR TITLE
Training with DALI

### PR DESCRIPTION
**Pull request by andrei5055**
Script to run training with and without Data Extension Library (DALI) for following networks:
**resnet-v1, resnet-v1b, resnet-v1b-normconv, resnet-v1b-normconv2, resnet, resnetv1, resnext**
To launch training use **scripts/classification/imagenet/test.sh**, which will install DALI

Following environment variables could be used:

export NUM_GPUS=N1 (all available GPUs will be used if NUM_GPUSis not defines OR set to less than 1)
export NETWORK=network_name  (by default **resnet-v1**)
export NO_DALI=--no-dali (if DALI should NOT be used for training, by default DALI will be used)
export NUM_EXAMPLES=N2  (by default 102400)
export NUM_EPOCHS=N3 (by default 1)

### CODE REVIEW

**Comment by TristonC** [comment]
@zhreshold Could you have someone to review the PR?

**Comment by zhreshold** [comment]
@andrei5055 can you explain more about these environment variables? BTW, do you have training logs and final performance metrics so that we can keep track of?

**Comment by andrei5055** [comment]
@zhreshold : After discussing this PR with @TristonC, I decided to abandon it and create a new one in which DALI will only be used as a data loader. In this case, the new PR will be much shorter and easier to analyze and accept. I am almost finished with this new PR and am planning to submit it today or tomorrow. 

The current PR was just an updated version of one of our Resnet training scripts. It contains many new files which are not really important for demonstrating the use of DALI.

**Comment by andrei5055** [comment]
A similar but much simpler PR was created: [DALI usage #1639](https://github.com/dmlc/gluon-cv/pull/1639)

**Pull request closed without merging**
