### PR TITLE
Fix custom image size for PSP segmentation net

### PR DESCRIPTION
**Pull request by cygerts**
Fixing a bug with custom image size for PSP segmentation net, response to this bug: https://github.com/dmlc/gluon-cv/issues/805. Unit tests added

### CODE REVIEW

**Comment by mli** [comment]
Job PR-826-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-826/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-826-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-826/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-826-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-826/4/index.html 
Code coverage of this PR:  vs. Master:

**Comment by hetong007** [comment]
@zhanghang1989

**Comment by zhanghang1989** [comment]
I only see the variable names are renamed. What is the benefit to do that?

**Comment by cygerts** [comment]
@zhanghang1989 - so this pull request is over 1 week old now and no one even bothered to look at the referenced bug https://github.com/dmlc/gluon-cv/issues/805. 

PSPNet (and DeepLab) nets do not work currently when you try to change default width and height of the input. I.e. the unit test I have added for PSPNet fails without that pull request. In this pull request I am fixing PSPNet. I can try to fix both DeepLabs as well, however the fix for those will be not that clean as for PSPNet, as the DeepLab code is not that clear to me in few places.

**Comment by zhanghang1989** [comment]
Thanks for the contribution! Could you also make changes to deeplab later?

**Pull request merged**
