### PR TITLE
Cythonized rpn target sampler

### PR DESCRIPTION
**Pull request by Jerryzcn**
cythonized rpn target sampler. Improve dataloader throughput.
Also removing mrcnn target generator as it is causing segfault. Will add it back once it is functional

For RPNTargetSampler, I have loop over it for 100 iters, and the average latency improved from 3.13 sec to 1.54 sec.

### CODE REVIEW

**Comment by Jerryzcn** [comment]
@Kh4L

**Comment by mli** [comment]
Job PR-1030-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1030/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by Kh4L** [comment]
What are the improvements you measured on single and multi GPU?

**Comment by zhreshold** [comment]
Please include unittest for consistency check, and benchmark result comparison.

**Comment by Jerryzcn** [comment]
> Please include unittest for consistency check, and benchmark result comparison.

Setting up cython build in testing seems really hard. Will do a benchmark

**Comment by Jerryzcn** [comment]
> What are the improvements you measured on single and multi GPU?

I did not observe any throughput improvements for either single or multi GPU training on MS COCO if # of workers per gpu is >= 4

**Comment by mli** [comment]
Job PR-1030-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1030/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by Jerryzcn** [comment]
Performance benchmark on p3.24dn
For single worker single gpu w/ batch_size=2:
2.8 samples/sec -> 2.9 samples/sec
For 2 workers single gpu:
5.4 samples/sec -> 5.6 samples/sec
For 4 workers single gpu:
9.3 samples/sec -> 9.4 samples/sec

For RPNTargetSampler itself, I have loop over it for 100 iters, and the average latency improved from 3.13 sec to 1.54 sec. It seems that RPNTargetSampler is not the bottleneck.

**Pull request merged**
