### PR TITLE
Monodepth2 tutorials

### PR DESCRIPTION
**Pull request by KuangHaofei**
This PR contain the tutorials of monodepth2. It is included two tutorials: demo_monodepth2, train_monodepth2.
This PR also fix some bugs of monodepth2.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1388-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1388/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1388-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1388/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1388-5 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1388/5/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1388-6 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1388/6/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1388-7 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1388/7/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1388-8 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1388/8/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1388-10 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1388/10/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1388-11 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1388/11/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1388-12 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1388/12/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1388-13 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1388/13/index.html 
Code coverage of this PR:  vs. Master:

**Comment by bryanyzhu** [comment]
Excellent job, well done! The PR looks good to me, I will merge it.

**Pull request merged**
