### PR TITLE
[WIP] Optional Syncbn for all BatchNorm layers in GluonCV

### PR DESCRIPTION
**Pull request by zhreshold**
This PR enables the optional syncBN version to replace all BatchNorm layers. In the future, GroupNorm for example can also be replace painlessly.

SSD relavant stuff finished.
Still working on the rest parts.

@eric-haibin-lin Ready for use if you need it ASAP for SSD training.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-521-9 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-521/9/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-521-10 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-521/10/index.html 
Code coverage of this PR:  vs. Master:

**Comment by hetong007** [comment]
The code looks good to me. However we may need to update the documentation to mention GroupNorm/InstanceNorm in the future.

**Comment by mli** [comment]
Job PR-521-11 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-521/11/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-521-12 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-521/12/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
