### PR TITLE
Reset class tutorial

### PR DESCRIPTION
**Pull request by zhreshold**

### CODE REVIEW

**Comment by mli** [comment]
Job PR-655-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-655/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-655-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-655/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by hetong007** [comment]
Since all detectors support `reset_classes` now, would you please help to remove this line as well:
https://github.com/dmlc/gluon-cv/blob/master/scripts/keypoints/simple_pose/demo.py#L40

**Comment by zhreshold** [comment]
Updated simple pose demo

**Comment by mli** [comment]
Job PR-655-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-655/4/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
