### PR TITLE
cifarwideresnet.py for MXNet-master

### PR DESCRIPTION
**Pull request by jinboci**
Cifarwideresnet for MXNet-master
Passed tests for `Cifarwideresnet` at `test_classification_models()` in test_model_zoo.py on my local sever.
Changes due to mxnet-master's different implementations from 1.7:
- `nn.HybridSequential` on mxnet-master does not accept the parameter `prefix`
- No `name_scope` defined in class Block on mxnet-master (block.py)

Changes due to latency Numpy operators:
- `npx.activation`
- `npx.dropout`

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1483-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1483/1/index.html 
Code coverage of this PR:  vs. Master:

**Review by zhreshold — COMMENTED** [review]
please fix conflicts before we can test and merge

**Comment by mli** [comment]
Job PR-1483-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1483/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1483-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1483/4/index.html 
Code coverage of this PR:  vs. Master:

**Review by zhreshold — APPROVED** [review]

**Pull request merged**
