### PR TITLE
fix sampler namespace

### PR DESCRIPTION
**Pull request by chinakook**
fix sampler SplitSortedBucketSampler namespace

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1525-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1525/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1525-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1525/2/index.html 
Code coverage of this PR:  vs. Master:

**Review by zhreshold — APPROVED** [review]

**Comment by zhreshold** [comment]
So the previous commit is somehow broken in training?

**Comment by chinakook** [comment]
> So the previous commit is somehow broken in training?
Yes

**Pull request merged**
