### PR TITLE
Scale lr and lr_warmup with batch size in M-RCNN training

### PR DESCRIPTION
**Pull request by Kh4L**

### CODE REVIEW

**Comment by Kh4L** [comment]
@Jerryzcn

**Comment by mli** [comment]
Job PR-988-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-988/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-988-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-988/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by Kh4L** [comment]
@zhreshold

**Pull request merged**
