### PR TITLE
Set static alloc for quantized models

### PR DESCRIPTION
**Pull request by xinyu-intel**
When gluon model hybridize with static_shape=True, static_alloc=True, cached_op with static mode will be used. For this situation, we should try to cache operator state for better performance. This PR is to enable this feature along with [MXNet #14785](https://github.com/apache/incubator-mxnet/pull/14785) to speed up gluon inference speed, especially for small batch sizes.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-755-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-755/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
I'll wait for https://github.com/apache/incubator-mxnet/pull/14785

**Comment by zhreshold** [comment]
merged together with apache/incubator-mxnet#14785

**Comment by pengzhao-intel** [comment]
@xinyu-intel do we need to update the performance in the tutorial?

**Comment by xinyu-intel** [comment]
@pengzhao-intel Throughput has a little bit improvement. Plan to update them along with some other models and waiting for 2nd gen Xeon online.

**Pull request merged**
