### PR TITLE
Add deeplabv3+b model for semantic segmentation

### PR DESCRIPTION
**Pull request by bryanyzhu**
Add deeplabv3+b model with wideresnet38 backbone for semantic segmentation on Cityscapes dataset.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-924-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-924/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhanghang1989** [comment]
The code looks good to me. Whether the training script is required in the same PR @zhreshold

**Comment by bryanyzhu** [comment]
I can use `scripts/segmentation/train.py` to train the new model, and inference is also fine. But to fully reproduce results (provide training bash and logs), it might take some time due to Mapillary pre-training and parameter tweaking. I can do it in next PR. But if it's required in the same PR, I will close this for now. 

Right now, I'm waiting for model store to upload and test again.

**Comment by mli** [comment]
Job PR-924-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-924/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-924-10 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-924/10/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-924-12 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-924/12/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-924-13 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-924/13/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
