### PR TITLE
Fix scripts, senet definition and add gamma init to resnext

### PR DESCRIPTION
**Pull request by hetong007**

### CODE REVIEW

**Comment by mli** [comment]
Job PR-247-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-247/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-247-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-247/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-247-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-247/4/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-247-5 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-247/5/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-247-6 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-247/6/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-247-7 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-247/7/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-247-8 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-247/8/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-247-9 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-247/9/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-247-10 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-247/10/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-247-11 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-247/11/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-247-12 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-247/12/index.html 
Code coverage of this PR:  vs. Master:

**Comment by hetong007** [comment]
@zhanghang1989 @Jerryzcn please review

**Comment by mli** [comment]
Job PR-247-16 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-247/16/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-247-17 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-247/17/index.html 
Code coverage of this PR:  vs. Master:

**Comment by hetong007** [comment]
I'm merging this for now. Reviews can be addressed in later issues/PRs.

**Pull request merged**
