### PR TITLE
add slides to website

### PR DESCRIPTION
**Pull request by zhreshold**

### CODE REVIEW

**Comment by mli** [comment]
Job PR-744-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-744/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-744-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-744/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
@hetong007 @piiswrong

**Comment by hetong007** [comment]
How about we add another layer of lists, i.e. "GluonCV Workshop in Tokyo, 2018", "ICCV 2019 Tutorial", then with links to each file?

**Comment by zhreshold** [comment]
@hetong007 Sounds good!

**Comment by mli** [comment]
Job PR-744-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-744/3/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
