### PR TITLE
DDP tutorial

### PR DESCRIPTION
**Pull request by bryanyzhu**
1. Modify root readme
2. Modify readme file under ./scripts/action-recognition/
3. Add DDP tutorial
4. Fix pretrained I3D tutorial: path, pretrained model and model.eval() problem.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1553-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1553/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
@bryanyzhu  THe DDP tutorial has unexpected code block: http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1553/1/build/examples_torch_action_recognition/ddp_pytorch.html

**Comment by bryanyzhu** [comment]
> @bryanyzhu THe DDP tutorial has unexpected code block: http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1553/1/build/examples_torch_action_recognition/ddp_pytorch.html

Thanks for letting me know, will modify it.

**Comment by mli** [comment]
Job PR-1553-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1553/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1553-6 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1553/6/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
