### PR TITLE
Improve hybridization in train_ssd.py

### PR DESCRIPTION
**Pull request by eric-haibin-lin**

### CODE REVIEW

**Comment by mli** [comment]
Job PR-489-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-489/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
@eric-haibin-lin How's the speed comparing with the old one?

**Comment by mli** [comment]
Job PR-489-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-489/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-489-5 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-489/5/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-489-6 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-489/6/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-489-7 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-489/7/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-489-7 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-489/7/index.html 
Code coverage of this PR:  vs. Master:

**Comment by Jerryzcn** [comment]
@eric-haibin-lin @zhreshold is this ready to be merged?

**Comment by eric-haibin-lin** [comment]
I think so. Although I find IO is the bottleneck for SSD

**Pull request merged**
