### PR TITLE
add resnext, resnest, mobilenet, squeezenet, densenet to API reference

### PR DESCRIPTION
**Pull request by ChaiBapchya**
Fixes https://github.com/dmlc/gluon-cv/issues/1400

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
@zhreshold unrelated error in unit-test.. this was a doc change..

**Comment by zhreshold** [comment]
retriggered

**Comment by mli** [comment]
Job PR-1430-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1430/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
@ChaiBapchya One minor issue caused the resnest/resnext not rendered in the docs, you need to import resne*t in https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/__init__.py#L24

**Comment by ChaiBapchya** [comment]
Added the required imports @zhreshold Thanks for pointing out.

**Comment by mli** [comment]
Job PR-1430-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1430/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
awesome, it looks way better, thanks @ChaiBapchya

**Pull request merged**
