### PR TITLE
Allow random_crop_with_constraints for empty bbx

### PR DESCRIPTION
**Pull request by djl11**
The function already accounts for the possibility of empty bbx input in line 67, but will break at line 104 if this is the case. Change this function to still return a valid constrained crop when no bounding box data is provided by the user, i.e. len(bbox) == 0.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-596-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-596/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by djl11** [comment]
If we set constraints = [ ] when len(bbx) == 0, then the for loop at line 70 would never be entered, and the scale and aspect ratio constraints would need to be replicated somewhere else in the function in order to get a correct constrained bounding box in the event that len(bbx) == 0.

In the current form, if no constraints are passed to the function, it defaults to None anyway, and is then handled in lines 57-65. If constraints are passed, but are not of the format specified in the function docstring, then the user of the function can expect an error. Either way, if len(bbx) == 0, a bounding box is returned which respects all constraints apart from the bounding box IOU constraint, which in this case makes no sense anyway.

The current version of the function seems to give more sensible behavior with minimal change, please correct me if/where you think I'm wrong though :)

**Comment by zhreshold** [comment]
LGTM, can you rebase to master? CI will restart once you push again @djl11

**Comment by djl11** [comment]
Sorry I was unaware that deleting my forked repository would automatically close this. I'm relatively new to pull requests. I have opened a new PR [here](https://github.com/dmlc/gluon-cv/pull/610), and will be more careful with my pull requests in future.

**Pull request closed without merging**
