### PR TITLE
Update chart pipeline

### PR DESCRIPTION
**Pull request by zhreshold**
Automatically fetch latest visualization charts rather than manual update.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-960-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-960/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-960-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-960/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-960-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-960/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
@hetong007 @zhanghang1989 @Jerryzcn @bryanyzhu Please take a look

**Comment by bryanyzhu** [comment]
Looks good to me, great work.

**Comment by hetong007** [comment]
So how is `https://zhiz-cache.s3.amazonaws.com/gluoncv-throughput-benchmarks/` maintained?

**Comment by zhreshold** [comment]
It will be automatically refreshed anytime I restart a ec2 instance with start script which run benchmark and uploading stuffs.

**Pull request merged**
