### PR TITLE
mkl for cpu test

### PR DESCRIPTION
**Pull request by zhanghang1989**

### CODE REVIEW

**Comment by xinyu-intel** [comment]
@zhanghang1989 Hi, could you try to use `pip install mxnet-cu90mkl==1.5.0b20181228`?

**Comment by zhanghang1989** [comment]
Thank you guys! Let me try that.

**Comment by zhanghang1989** [comment]
It fails in `test_data_transforms.test_transforms_presets_ssd`, any thoughts?

**Comment by zhanghang1989** [comment]
> @zhanghang1989 okay, thanks for your trying. But I cannot reproduce locally. Can you reproduce this in your own machine? May I know your Jenkins machine's configurations?

Thanks for the fast reply. I have another error using local machine:
```
............OMP: Error #15: Initializing libiomp5.so, but found libiomp5.so already initialized.
OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
Aborted (core dumped)
```

**Comment by xinyu-intel** [comment]
This OMP Error is due to duplicated omp runtime library (libiopm5.so in anaconda and mkldnn). Feel free to export `KMP_DUPLICATE_LIB_OK=TRUE` to solve this problem.

**Comment by zhanghang1989** [comment]
> This OMP Error is due to duplicated omp runtime library (libiopm5.so in anaconda and mkldnn). Feel free to export `KMP_DUPLICATE_LIB_OK=TRUE` to solve this problem.

Thanks!  I rerun my local test and it went through. Something is wrong with the CI server

**Comment by zhreshold** [comment]
@zhanghang1989 You can rebase MASTER and try again, I found previous conda env includes multiple copy of mxnet versions.

**Comment by zhanghang1989** [comment]
@zhreshold I just merged from master, but it still fails in unit test of ssd preset.

**Comment by zhreshold** [comment]
Seems like there's a memory issue with mkl variants

```
test_data_transforms.test_transforms_presets_ssd ... *** Error in `/var/lib/jenkins/miniconda3/envs/gluon_cv_py2_test/bin/python': malloc(): memory corruption: 0x00007f6a6101e3f0 ***

```

**Comment by pengzhao-intel** [comment]
Thanks @zhanghang1989 @zhreshold for testing. please help close this PR and we will file a new one to debug.

@zhennanqin please file a new PR and debug this issue :)

**Comment by zhreshold** [comment]
Thanks for the effort, closing this for now

**Pull request closed without merging**
