### PR TITLE
Model links

### PR DESCRIPTION
**Pull request by zhreshold**

### CODE REVIEW

**Comment by mli** [comment]
Job PR-385-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-385/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
Classification links depend on #384

**Comment by mli** [comment]
Job PR-385-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-385/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-385-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-385/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-385-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-385/4/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-385-5 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-385/5/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
