### PR TITLE
Refactor k400 dataloader

### PR DESCRIPTION
**Pull request by bryanyzhu**
This PR refactors K400 dataloader, inherited from VideoClsCustom to make code cleaner. Will do other datasets in later PRs.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1165-6 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1165/6/index.html 
Code coverage of this PR:  vs. Master:

**Comment by bryanyzhu** [comment]
@wuxun-zhang @zhreshold Recently, CI python3 test often fails at this function [`test_quantized_action_recognition_models`](https://github.com/dmlc/gluon-cv/blob/master/tests/unittests/test_model_zoo.py#L660). The error is OOM, 

```
mxnet.base.MXNetError: [06:54:13] src/storage/./cpu_device_storage.h:75: Failed to allocate CPU Memory
```
I tried to reduce the input size from 224 to 56, but still encounters OOM issue. I looked at the CPU memory, the peak usage can be 19G. If I remove the test of `resnet50_v1b_kinetics400_int8 `, the issue will be resolved. Please let me know what are your thoughts. Thank you.

**Comment by mli** [comment]
Job PR-1165-8 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1165/8/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
If int8 model is occupying more mem than fp32 then there must be something wrong with the quantization, can you take a look @wuxun-zhang

**Comment by wuxun-zhang** [comment]
> If int8 model is occupying more mem than fp32 then there must be something wrong with the quantization, can you take a look @wuxun-zhang

Sorry for the late reply. I will take a look at this problem.

**Comment by wuxun-zhang** [comment]
I tried to collect some profiling results for `resnet50_v1b_kinetics400` model. Below is the command I used.

```
export MXNET_PROFILER_AUTOSTART=1
export MXNET_PROFILER_MODE=1
export MXNET_EXEC_BULK_EXEC_INFERENCE=0
export MXNET_EXEC_BULK_EXEC_TRAIN=0

export KMP_AFFINITY=granularity=fine,noduplicates,compact,1,0
export OMP_NUM_THREADS=28

# FP32
numactl --physcpubind=0-27 --membind=0 python test_recognizer.py --model resnet50_v1b_kinetics400 --dataset kinetics400 --new-height 256 --new-width 340 --num-segments 7 --benchmark --batch-size 1

# INT8
numactl --physcpubind=0-27 --membind=0 python test_recognizer.py --model resnet50_v1b_kinetics400 --dataset kinetics400 --new-height 256 --new-width 340 --num-segments 7 --benchmark --batch-size 1 --quantized
```

Below is the output of `profiler.dumps()`.

**FP32**
```
Profile Statistics:
        Note the difference in units for different entries.
Device Storage
=================
Name                          Total Count    Min Use  (kB)    Max Use  (kB)    Avg Use  (kB)
----                          -----------    -------------    -------------    -------------
Memory: cpu/0                       64081        5695.1040      296420.7500      145362.8281
```

**INT8**
```
Profile Statistics:
        Note the difference in units for different entries.
Device Storage
=================
Name                          Total Count    Min Use  (kB)    Max Use  (kB)    Avg Use  (kB)
----                          -----------    -------------    -------------    -------------
Memory: cpu/0                       47459           0.0040       16191.0000        8095.4980
```

From above we can see that int8 model did save much memory consumption compared with FP32 model.

**Comment by zhreshold** [comment]
Is it possible that running models in sequential will cause memory not released properly: https://github.com/dmlc/gluon-cv/blob/master/tests/unittests/test_model_zoo.py#L660?

**Comment by bryanyzhu** [comment]
Just to add one comment. 

Last time, in order to make PR failure less frequently, I remove res50 model from this function `test_quantized_action_recognition_models`. The situation is indeed much better, but still fails once  in the last week. This means either running quantized model in sequential cause memory not released properly, or the CI machine has some unknown process running at the same time.

**Pull request merged**
