### PR TITLE
Fixed bug where mobilenet always uses BatchNorm even with different norm_layer parameter input

### PR DESCRIPTION
**Pull request by mightydeveloper**
Modified 'norm_layer' to use the 'norm_layer' defined at a higher level, 
instead of always using BatchNorm

I think this modification is the intended code

### CODE REVIEW

**Comment by mli** [comment]
Job PR-753-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-753/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mightydeveloper** [comment]
Sure! I'll reference mobilenet v2 and try to make some changes

**Comment by mightydeveloper** [comment]
It seems that both MobileNetV1 and MobileNetV2 hard-assigns `norm_kwargs=None` even though its caller already accepts norm_kwargs from higher level. I'll try to make all `norm_kwargs` to use higher level as well. (just like `norm_layer`). If this is not intended, plz let me know

**Comment by mli** [comment]
Job PR-753-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-753/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
@mightydeveloper Looks good! It's merged now.

**Pull request merged**
