### PR TITLE
Add hashtags for pretrained models

### PR DESCRIPTION
**Pull request by hetong007**
Add hashtag for pretrained model loading for
- reproducible research
- distinguish differently generated params

### CODE REVIEW

**Comment by zhreshold** [comment]
I would prefer the best models to be default option, IMO it applies to the majority use cases.

**Comment by mli** [comment]
Job PR-376-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-376/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-376-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-376/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-376-6 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-376/6/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-376-7 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-376/7/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
