### PR TITLE
Update model_zoo models with new NumPy operators

### PR DESCRIPTION
**Pull request by jinboci**
Update model_zoo with new NumPy operators (Not yet completed)
- gluoncv/model_zoo/alexnet.py
- gluoncv/model_zoo/attention.py
- gluoncv/model_zoo/cifarresnet.py
- gluoncv/model_zoo/cifarresnext.py
- gluoncv/model_zoo/cifarwiderresnet.py
- gluoncv/model_zoo/deeplabv3b_plus.py
- gluoncv/model_zoo/residual_attentionnet.py
- gluoncv/model_zoo/resnest.py
- gluoncv/model_zoo/resnext.py
- gluoncv/model_zoo/resnetv1b.py
- gluoncv/model_zoo/se_resnet.py
- gluoncv/nn/dropblock.py
- gluoncv/nn/gn.py
- gluoncv/nn/splat.py

Add fixs to
- gluoncv/model_zoo/resnet.py

Enable test cases:
- tests/model_zoo/test_model_zoo.py: 
  - test_classification_models()
  - test_segmentation_models() (partly)
  - test_imagenet_models() (partly)
- tests/unittests/test_nn.py:
  - test_groupnorm()

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1433-20 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1433/20/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1433-21 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1433/21/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1433-22 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1433/22/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1433-23 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1433/23/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1433-24 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1433/24/index.html 
Code coverage of this PR:  vs. Master:

**Comment by jinboci** [comment]
This pull request is already out-of-date. The branch [`dmlc:numpy`](https://github.com/dmlc/gluon-cv/tree/numpy) is now supporting [MXNet 2.0](https://github.com/apache/incubator-mxnet), while this PR is based on [v1.7.x](https://github.com/apache/incubator-mxnet/tree/v1.7.x). Please check #1473 #1482 #1483 #1486 #1493 #1494 #1503 #1504 #1506 for current implementations.

**Pull request closed without merging**
