### PR TITLE
[WIP] Update plot 0.4

### PR DESCRIPTION
**Pull request by zhreshold**
- [x] Add pruned resnet table
- [x] Update plots

### CODE REVIEW

**Comment by mli** [comment]
Job PR-672-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-672/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-672-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-672/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by hetong007** [comment]
LGTM. Just a question: do we have any literature to refer the new table to? It may be too vague for users seeking for more information.

**Comment by mli** [comment]
Job PR-672-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-672/4/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-672-5 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-672/5/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
