### PR TITLE
fix a typo in docs

### PR DESCRIPTION
**Pull request by chongruo**
fix a typo in docs #1301

### CODE REVIEW

**Comment by bryanyzhu** [comment]
@chongruo The pylint error is being fixed in PR #1303.

**Comment by chongruo** [comment]
> @chongruo The pylint error is being fixed in PR #1303.

thanks!

**Comment by mli** [comment]
Job PR-1302-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1302/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by bryanyzhu** [comment]
Hi, is this PR still valid? Let me know if you want to merge or WIP? Thanks.

**Comment by mli** [comment]
Job PR-1302-5 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1302/5/index.html 
Code coverage of this PR:  vs. Master:

**Comment by chongruo** [comment]
> Hi, is this PR still valid? Let me know if you want to merge or WIP? Thanks.

@bryanyzhu It is ready to merge

**Pull request merged**
