### PR TITLE
update application table

### PR DESCRIPTION
**Pull request by mli**

### CODE REVIEW

**Comment by mli** [comment]
Job PR-383-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-383/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
The render failed somehow

**Comment by zhreshold** [comment]
should start with
```
.. raw:: html
```
probably

**Comment by mli** [comment]
Job PR-383-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-383/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
@zhreshold  pretty ugly at this moment. can you please try to hack the html to 

1. make the images smaller
2. vertically center align text
3. increase the cell pad

**Comment by mli** [comment]
never mind, i found the solution

**Comment by mli** [comment]
Job PR-383-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-383/4/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-383-8 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-383/8/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
