### PR TITLE
switch to mxnet-cu92mkl

### PR DESCRIPTION
**Pull request by ZhennanQin**

### CODE REVIEW

**Comment by ZhennanQin** [comment]
@zhreshold After some investigation, found that it's crashed in mxnet::op::BipartiteMatchingForward<mshadow::cpu>. This op doesn't relate to mkl or mkldnn , but possibly has memory access bug exposed by mkl build. Do you know any risk for this op causing heap corruption? Thanks in advance.

**Comment by zhreshold** [comment]
@ZhennanQin Can you try the latest nightly build of mkl cu92? Recently I just merged a PR fixing memory issue of BipartiteMatching OP

https://github.com/apache/incubator-mxnet/pull/13727

**Comment by mli** [comment]
Job PR-578-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-578/4/index.html 
Code coverage of this PR:  vs. Master:

**Comment by ZhennanQin** [comment]
@zhreshold After updating mxnet-cu92mkl to 1.5.0b20190115, CI can pass. Hurray! Thanks for pointing me the fix.

Do you have any other trouble for using mxnet mkl build?

**Comment by zhreshold** [comment]
Looks good as long as CI has no complains. I will keep this one open for one day in case @hetong007 and @zhanghang1989 have extra prompt

**Comment by zhreshold** [comment]
@pengzhao-intel It was actually picked into 1.4.x by https://github.com/apache/incubator-mxnet/pull/13900

**Comment by pengzhao-intel** [comment]
@wuxun-zhang please help test how much performance benefit we can gain after changing MKLDNN backend.
@zhreshold any recommended benchmark scripts for benchmarking or only use the CI tests?

**Comment by zhreshold** [comment]
There's no existing benchmark scripts, but I think we can creating some using exsiting inference code.

**Comment by pengzhao-intel** [comment]
@zhreshold thanks a lot. Ping us when the code is ready.

**Comment by pengzhao-intel** [comment]
@zhreshold could you help merge the PR? thanks.

**Pull request merged**
