### PR TITLE
model zoo for danet and fastscnn

### PR DESCRIPTION
**Pull request by bryanyzhu**
This PR adds model zoo page for danet and fastscnn. update readme as well.

### CODE REVIEW

**Comment by bryanyzhu** [comment]
@zhreshold Hi, this PR fails at sanity check, saying `ModuleNotFoundError: No module named 'pylint'`. Any suggestions? Thank you.

**Comment by zhreshold** [comment]
@bryanyzhu  Not sure why it happens, but check this out: https://github.com/dmlc/gluon-cv/pull/1285

**Comment by mli** [comment]
Job PR-1284-5 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1284/5/index.html 
Code coverage of this PR:  vs. Master:

**Comment by bryanyzhu** [comment]
@zhreshold Thanks a lot, it looks like your solution is working. I just merged #1285 .

**Comment by mli** [comment]
Job PR-1284-7 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1284/7/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
