### PR TITLE
Bug fix with crop_size and base_size on segmentation dataset loaders.

### PR DESCRIPTION
**Pull request by ragavvenkatesan**
Probably Hang Zhang is going to do this on a new PR With cityscapes.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-323-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-323/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhanghang1989** [comment]
Thanks @ragavvenkatesan for pointing out this issue and contributing! This issue was introduced by a previous PR for Cityscapes dataset. It will be fixed in the PR https://github.com/dmlc/gluon-cv/pull/334 , and the changes will be compatible with other changes too.

**Comment by mli** [comment]
Job PR-323-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-323/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-323-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-323/4/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-323-5 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-323/5/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-323-6 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-323/6/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-323-7 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-323/7/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-323-8 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-323/8/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhanghang1989** [comment]
closing this PR in favor of https://github.com/dmlc/gluon-cv/pull/334

**Pull request closed without merging**
