### PR TITLE
add hrnet18 and hrnet64\n add hrnet pretrained models

### PR DESCRIPTION
**Pull request by chinakook**
1. add hrnet18 and hrnet64
2. add hrnet pretrained models converted from torch
[model download link](https://pan.baidu.com/s/1-JkOwzihXtuBbpTUqOMbGw) code: lz2f

### CODE REVIEW

**Comment by chinakook** [comment]
@zhreshold

**Comment by mli** [comment]
Job PR-1243-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1243/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
@chinakook The baidu pan only contains pth files, am I missing something here?

**Comment by chinakook** [comment]
Sorry for that. It's revised.
[model download link](https://pan.baidu.com/s/1-JkOwzihXtuBbpTUqOMbGw) code: lz2f

**Comment by chinakook** [comment]
close due to hrnet with bilinear and nearest arguments cannot be hybridized successfully. I'll reopen it after it's solved.

**Comment by chinakook** [comment]
After this fix https://github.com/apache/incubator-tvm/pull/5238 . the hrnet can be successfully hybridized.

**Comment by mli** [comment]
Job PR-1243-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1243/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1243-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1243/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
@chinakook  Thanks for updating!. I am downloading the weights from baidu pan, which takes longer than I expect. 
I will update once I've tested the weights.

**Comment by mli** [comment]
Job PR-1243-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1243/4/index.html 
Code coverage of this PR:  vs. Master:

**Comment by chinakook** [comment]
@zhreshold Yeah, that's all.

**Pull request merged**
