### PR TITLE
enable quantized pspnet & deeplab model

### PR DESCRIPTION
**Pull request by wuxun-zhang**
This PR is to enable more quantized segmentation models, including pspnet and deeplab. Also, we also used the `entropy` mode for calibrating INT8 models, which will introduce improvement of accuracy and mIoU.
@pengzhao-intel @xinyu-intel @zhanghang1989 @zhreshold

### CODE REVIEW

**Comment by mli** [comment]
Job PR-922-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-922/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-922-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-922/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by xinyu-intel** [comment]
@zhreshold Please help review and we can include these models in the coming release version:)

**Comment by zhreshold** [comment]
looks good.
@zhanghang1989 @bryanyzhu Feel free to comment and I will merge it this afternoon

**Comment by bryanyzhu** [comment]
Looks good to me.

**Pull request merged**
