### PR TITLE
Fix windows bug with filename

### PR DESCRIPTION
**Pull request by ThomasDelteil**
windows does not like 'street_small.jpg?raw=true' as filename.
see: https://discuss.mxnet.io/t/invalid-argument-street-small-jpg-raw-true/1065

https://github.com/dmlc/gluon-cv/issues/132

### CODE REVIEW

**Comment by ThomasDelteil** [comment]
@zhreshold sure, could you point me to the right direction I can't find it in the repo?

**Comment by zhreshold** [comment]
https://github.com/dmlc/gluon-cv/blob/fbc909a84ff5f24a01ce261211d6aab55b416a3f/docs/tutorials/detection/demo_ssd.py#L43
It's the file that generates the tutorial on website.

**Comment by ThomasDelteil** [comment]
@zhreshold isn't it the file that I have updated already?

**Comment by zhreshold** [comment]
My bad, it should be fine. CI is down due to GPU memory issue.

**Pull request merged**
