### PR TITLE
pascal_context.py

### PR DESCRIPTION
**Pull request by BebDong**
pascal_context.py implementing PASCAL Context semantic segmentation dataset with 59 (+background) semantic labels

### CODE REVIEW

**Comment by mli** [comment]
Job PR-829-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-829/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by hetong007** [comment]
@zhanghang1989

**Comment by zhanghang1989** [comment]
Please add corresponding prepare script and unitest.

**Comment by mli** [comment]
Job PR-829-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-829/4/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-829-5 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-829/5/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-829-6 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-829/6/index.html 
Code coverage of this PR:  vs. Master:

**Comment by BebDong** [comment]
@zhanghang1989

**Comment by BebDong** [comment]
@zhanghang1989 Pascal Context segmentation dataset loader needs the extra Detail API which has been prepared at the corresponding prepare script. However the data loader(pascal_context.py) and corresponding unit test(test_data_datasets.test_pcontext_segmentation) failed at Jenkins Unit Test. How should I handle it?

**Comment by zhanghang1989** [comment]
Thanks for contributing. Please also make an alias to https://github.com/dmlc/gluon-cv/blob/bd59b6cd252dd2da6d5eca1061e8f2940a9a34c8/gluoncv/data/__init__.py#L28

Provide a link to the original code where is adapted, which I believe is from https://github.com/zhanghang1989/Pytorch-Encoding

**Comment by BebDong** [comment]
@zhanghang1989 
Thanks for your generously help and reminding since this is my very first attempting to contribute at github.
And alias and original reference link has been added, but still failed because of no detail module when importing.

**Comment by zhanghang1989** [comment]
Could you use `try_import` function to avoid extra dependencies?
https://github.com/dmlc/gluon-cv/blob/master/gluoncv/utils/filesystem.py#L20-L53

**Comment by zhanghang1989** [comment]
Seems there is a pylint error. Could you fix that?

**Pull request closed without merging**
