### PR TITLE
Add light mask rcnn to docs and model store

### PR DESCRIPTION
**Pull request by Jerryzcn**

### CODE REVIEW

**Comment by hetong007** [comment]
LGTM if it passes CI.

**Comment by zhreshold** [comment]
CI failed, I guess `mask_rcnn_resnet18_v1b_coco` definition is incorrect which loads resnet50 pretrained models.

**Comment by Jerryzcn** [comment]
is there anyway to change the model weight's prefix, i think the prefixes are setup incorrectly

**Comment by mli** [comment]
Job PR-799-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-799/2/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
