### PR TITLE
Add short demo to classification landing page

### PR DESCRIPTION
**Pull request by hetong007**

### CODE REVIEW

**Comment by mli** [comment]
Job PR-384-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-384/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-384-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-384/4/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
@hetong007  I think we can have a default image saved in `docs/_static`, users can right click and save it, it's better than searching for an image themselves otherwise

**Comment by hetong007** [comment]
@zhreshold how about this one: https://gluon-cv.mxnet.io/_static/image-classification.png ? We can use it for all tasks but instance segmentation.

**Comment by mli** [comment]
istock-903592682

here is the raw image

**Comment by mli** [comment]
Some modifications:

1. The following example requires GluonCV>=?? and MXNet>=??. Please follow our installation guideline to install or upgrade GluonCV and MXNet if necessary. 
2. Prepare an image by yourself or use [our sample image](). You can save the image into filename classification-demon.jpg in your working directory or change the filename in the source codes if you use an another name.
3. Use a pre-trained model. A model is specified by its name.

Let’s try it out!

```python
import mxnet as mx
import gluoncv

# you can change it to your image filename
filename = 'classification-demo.jpg'
# you may modify it to switch to another model. The name is case-insensitive  
model_name = 'ResNet50_v1d'  
# download and load the pre-trained model
net = gluoncv.model_zoo.get_model(model_name, pretrained=True)  
# load image
img = mx.image.imread(filename)  
# apply default data preprocessing
transformed_img = gluoncv.data.transforms.presets.imagenet.transform_eval(img)  
# run forward pass to obtain the predicted score for each class
pred = net(transformed_img)  
# find the class index with the highest score
predicted_index = int(pred.argmax(axis=1).asscalar())  
# print the class name
print("Classified to be %s"%(net.classes[predicted_index])) 
```

**Comment by mli** [comment]
In addtion, please all print the confidence score. Aslo provide another sample code to print the top-5 results

**Comment by mli** [comment]
Job PR-384-5 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-384/5/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-384-6 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-384/6/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
