### PR TITLE
Fix MobileNetV2 to follow official implementation

### PR DESCRIPTION
**Pull request by mightydeveloper**
Although not explicitly written in the paper, it seems that the first bottleneck layer in MobileNet V2 does not start with 1x1 convolution (expansion part), but rather skips 1x1 expansion convolution and starts with 3x3 depth-wise convolution. 
The official implementation I referenced is 
https://github.com/tensorflow/models/blob/4b4dbad1e983543f196cf7909710775059af7e92/research/slim/nets/mobilenet/mobilenet_v2.py#L60
and particular expansion conv block is implemented in
https://github.com/tensorflow/models/blob/4b4dbad1e983543f196cf7909710775059af7e92/research/slim/nets/mobilenet/conv_blocks.py#L163

I believe this mistake is quite common (since the paper wasn't explicit about this)
(for example, [some PyTorch implementation](https://github.com/tonylins/pytorch-mobilenet-v2/issues/2) made the same mistake)

Although it is ambiguous whether this is correct at this point, 
we can calculate total Multiply-Adds (FLOPS) to see which one is more correct.
The current gluon-cv implementation has 313.62 Million FLOPS,
while removing this one 1x1 conv layer makes 300.77 Million FLOPS which is around the same with official MobileNetV2 paper (Official paper says 300M FLOPS).
Since [ShuffleNetV2](https://arxiv.org/abs/1807.11164) mentions that their implementation of MobileNet V2 is around 301 M FLOPS, I believe this implementation of removing the first (expansion) 1x1 convolution in the first bottleneck layer is correct. (which makes 300.77 M FLOPS)

To support the claim,
[Torchvision implementation](https://github.com/pytorch/vision/blob/ae81313fa8876b2fabae7abf2c81a9182e99a8ca/torchvision/models/mobilenet.py#L24) also removes this conv layer.
Also, [some other implementations](https://github.com/d-li14/mobilenetv2.pytorch/blob/8f7386d900867a28464e0cfd4d749dff2ee290a2/models/imagenet/mobilenetv2.py#L59) also follow this.

Please feel free to discuss and let me know if I made any mistake

### CODE REVIEW

**Comment by mightydeveloper** [comment]
It seems the build/test fails because it has conflicts with loading pre-trained parameters. If the above claim correct, how should I proceed to fix build/test failure?

**Comment by mightydeveloper** [comment]
Here is FLOPS summary for reference
# Before - Current GluonCV implementation
```
-----------------------------------------------------------------------------------------------
        Layer (type)                                Output Shape         Param #  Multiply-Adds
===============================================================================================
               Input                            (1, 3, 224, 224)               0              0
            Conv2D-1                           (1, 32, 112, 112)             864     10,838,016
         BatchNorm-2                           (1, 32, 112, 112)             128              0
             RELU6-3                           (1, 32, 112, 112)               0              0
            Conv2D-4                           (1, 32, 112, 112)           1,024     12,845,056
         BatchNorm-5                           (1, 32, 112, 112)             128              0
             RELU6-6                           (1, 32, 112, 112)               0              0
            Conv2D-7                           (1, 32, 112, 112)             288      3,612,672
         BatchNorm-8                           (1, 32, 112, 112)             128              0
             RELU6-9                           (1, 32, 112, 112)               0              0
           Conv2D-10                           (1, 16, 112, 112)             512      6,422,528
        BatchNorm-11                           (1, 16, 112, 112)              64              0
 LinearBottleneck-12                           (1, 16, 112, 112)               0              0
           Conv2D-13                           (1, 96, 112, 112)           1,536     19,267,584
        BatchNorm-14                           (1, 96, 112, 112)             384              0
            RELU6-15                           (1, 96, 112, 112)               0              0
           Conv2D-16                             (1, 96, 56, 56)             864      2,709,504
        BatchNorm-17                             (1, 96, 56, 56)             384              0
            RELU6-18                             (1, 96, 56, 56)               0              0
           Conv2D-19                             (1, 24, 56, 56)           2,304      7,225,344
        BatchNorm-20                             (1, 24, 56, 56)              96              0
 LinearBottleneck-21                             (1, 24, 56, 56)               0              0
           Conv2D-22                            (1, 144, 56, 56)           3,456     10,838,016
        BatchNorm-23                            (1, 144, 56, 56)             576              0
            RELU6-24                            (1, 144, 56, 56)               0              0
           Conv2D-25                            (1, 144, 56, 56)           1,296      4,064,256
        BatchNorm-26                            (1, 144, 56, 56)             576              0
            RELU6-27                            (1, 144, 56, 56)               0              0
           Conv2D-28                             (1, 24, 56, 56)           3,456     10,838,016
        BatchNorm-29                             (1, 24, 56, 56)              96              0
 LinearBottleneck-30                             (1, 24, 56, 56)               0              0
           Conv2D-31                            (1, 144, 56, 56)           3,456     10,838,016
        BatchNorm-32                            (1, 144, 56, 56)             576              0
            RELU6-33                            (1, 144, 56, 56)               0              0
           Conv2D-34                            (1, 144, 28, 28)           1,296      1,016,064
        BatchNorm-35                            (1, 144, 28, 28)             576              0
            RELU6-36                            (1, 144, 28, 28)               0              0
           Conv2D-37                             (1, 32, 28, 28)           4,608      3,612,672
        BatchNorm-38                             (1, 32, 28, 28)             128              0
 LinearBottleneck-39                             (1, 32, 28, 28)               0              0
           Conv2D-40                            (1, 192, 28, 28)           6,144      4,816,896
        BatchNorm-41                            (1, 192, 28, 28)             768              0
            RELU6-42                            (1, 192, 28, 28)               0              0
           Conv2D-43                            (1, 192, 28, 28)           1,728      1,354,752
        BatchNorm-44                            (1, 192, 28, 28)             768              0
            RELU6-45                            (1, 192, 28, 28)               0              0
           Conv2D-46                             (1, 32, 28, 28)           6,144      4,816,896
        BatchNorm-47                             (1, 32, 28, 28)             128              0
 LinearBottleneck-48                             (1, 32, 28, 28)               0              0
           Conv2D-49                            (1, 192, 28, 28)           6,144      4,816,896
        BatchNorm-50                            (1, 192, 28, 28)             768              0
            RELU6-51                            (1, 192, 28, 28)               0              0
           Conv2D-52                            (1, 192, 28, 28)           1,728      1,354,752
        BatchNorm-53                            (1, 192, 28, 28)             768              0
            RELU6-54                            (1, 192, 28, 28)               0              0
           Conv2D-55                             (1, 32, 28, 28)           6,144      4,816,896
        BatchNorm-56                             (1, 32, 28, 28)             128              0
 LinearBottleneck-57                             (1, 32, 28, 28)               0              0
           Conv2D-58                            (1, 192, 28, 28)           6,144      4,816,896
        BatchNorm-59                            (1, 192, 28, 28)             768              0
            RELU6-60                            (1, 192, 28, 28)               0              0
           Conv2D-61                            (1, 192, 14, 14)           1,728        338,688
        BatchNorm-62                            (1, 192, 14, 14)             768              0
            RELU6-63                            (1, 192, 14, 14)               0              0
           Conv2D-64                             (1, 64, 14, 14)          12,288      2,408,448
        BatchNorm-65                             (1, 64, 14, 14)             256              0
 LinearBottleneck-66                             (1, 64, 14, 14)               0              0
           Conv2D-67                            (1, 384, 14, 14)          24,576      4,816,896
        BatchNorm-68                            (1, 384, 14, 14)           1,536              0
            RELU6-69                            (1, 384, 14, 14)               0              0
           Conv2D-70                            (1, 384, 14, 14)           3,456        677,376
        BatchNorm-71                            (1, 384, 14, 14)           1,536              0
            RELU6-72                            (1, 384, 14, 14)               0              0
           Conv2D-73                             (1, 64, 14, 14)          24,576      4,816,896
        BatchNorm-74                             (1, 64, 14, 14)             256              0
 LinearBottleneck-75                             (1, 64, 14, 14)               0              0
           Conv2D-76                            (1, 384, 14, 14)          24,576      4,816,896
        BatchNorm-77                            (1, 384, 14, 14)           1,536              0
            RELU6-78                            (1, 384, 14, 14)               0              0
           Conv2D-79                            (1, 384, 14, 14)           3,456        677,376
        BatchNorm-80                            (1, 384, 14, 14)           1,536              0
            RELU6-81                            (1, 384, 14, 14)               0              0
           Conv2D-82                             (1, 64, 14, 14)          24,576      4,816,896
        BatchNorm-83                             (1, 64, 14, 14)             256              0
 LinearBottleneck-84                             (1, 64, 14, 14)               0              0
           Conv2D-85                            (1, 384, 14, 14)          24,576      4,816,896
        BatchNorm-86                            (1, 384, 14, 14)           1,536              0
            RELU6-87                            (1, 384, 14, 14)               0              0
           Conv2D-88                            (1, 384, 14, 14)           3,456        677,376
        BatchNorm-89                            (1, 384, 14, 14)           1,536              0
            RELU6-90                            (1, 384, 14, 14)               0              0
           Conv2D-91                             (1, 64, 14, 14)          24,576      4,816,896
        BatchNorm-92                             (1, 64, 14, 14)             256              0
 LinearBottleneck-93                             (1, 64, 14, 14)               0              0
           Conv2D-94                            (1, 384, 14, 14)          24,576      4,816,896
        BatchNorm-95                            (1, 384, 14, 14)           1,536              0
            RELU6-96                            (1, 384, 14, 14)               0              0
           Conv2D-97                            (1, 384, 14, 14)           3,456        677,376
        BatchNorm-98                            (1, 384, 14, 14)           1,536              0
            RELU6-99                            (1, 384, 14, 14)               0              0
          Conv2D-100                             (1, 96, 14, 14)          36,864      7,225,344
       BatchNorm-101                             (1, 96, 14, 14)             384              0
LinearBottleneck-102                             (1, 96, 14, 14)               0              0
          Conv2D-103                            (1, 576, 14, 14)          55,296     10,838,016
       BatchNorm-104                            (1, 576, 14, 14)           2,304              0
           RELU6-105                            (1, 576, 14, 14)               0              0
          Conv2D-106                            (1, 576, 14, 14)           5,184      1,016,064
       BatchNorm-107                            (1, 576, 14, 14)           2,304              0
           RELU6-108                            (1, 576, 14, 14)               0              0
          Conv2D-109                             (1, 96, 14, 14)          55,296     10,838,016
       BatchNorm-110                             (1, 96, 14, 14)             384              0
LinearBottleneck-111                             (1, 96, 14, 14)               0              0
          Conv2D-112                            (1, 576, 14, 14)          55,296     10,838,016
       BatchNorm-113                            (1, 576, 14, 14)           2,304              0
           RELU6-114                            (1, 576, 14, 14)               0              0
          Conv2D-115                            (1, 576, 14, 14)           5,184      1,016,064
       BatchNorm-116                            (1, 576, 14, 14)           2,304              0
           RELU6-117                            (1, 576, 14, 14)               0              0
          Conv2D-118                             (1, 96, 14, 14)          55,296     10,838,016
       BatchNorm-119                             (1, 96, 14, 14)             384              0
LinearBottleneck-120                             (1, 96, 14, 14)               0              0
          Conv2D-121                            (1, 576, 14, 14)          55,296     10,838,016
       BatchNorm-122                            (1, 576, 14, 14)           2,304              0
           RELU6-123                            (1, 576, 14, 14)               0              0
          Conv2D-124                              (1, 576, 7, 7)           5,184        254,016
       BatchNorm-125                              (1, 576, 7, 7)           2,304              0
           RELU6-126                              (1, 576, 7, 7)               0              0
          Conv2D-127                              (1, 160, 7, 7)          92,160      4,515,840
       BatchNorm-128                              (1, 160, 7, 7)             640              0
LinearBottleneck-129                              (1, 160, 7, 7)               0              0
          Conv2D-130                              (1, 960, 7, 7)         153,600      7,526,400
       BatchNorm-131                              (1, 960, 7, 7)           3,840              0
           RELU6-132                              (1, 960, 7, 7)               0              0
          Conv2D-133                              (1, 960, 7, 7)           8,640        423,360
       BatchNorm-134                              (1, 960, 7, 7)           3,840              0
           RELU6-135                              (1, 960, 7, 7)               0              0
          Conv2D-136                              (1, 160, 7, 7)         153,600      7,526,400
       BatchNorm-137                              (1, 160, 7, 7)             640              0
LinearBottleneck-138                              (1, 160, 7, 7)               0              0
          Conv2D-139                              (1, 960, 7, 7)         153,600      7,526,400
       BatchNorm-140                              (1, 960, 7, 7)           3,840              0
           RELU6-141                              (1, 960, 7, 7)               0              0
          Conv2D-142                              (1, 960, 7, 7)           8,640        423,360
       BatchNorm-143                              (1, 960, 7, 7)           3,840              0
           RELU6-144                              (1, 960, 7, 7)               0              0
          Conv2D-145                              (1, 160, 7, 7)         153,600      7,526,400
       BatchNorm-146                              (1, 160, 7, 7)             640              0
LinearBottleneck-147                              (1, 160, 7, 7)               0              0
          Conv2D-148                              (1, 960, 7, 7)         153,600      7,526,400
       BatchNorm-149                              (1, 960, 7, 7)           3,840              0
           RELU6-150                              (1, 960, 7, 7)               0              0
          Conv2D-151                              (1, 960, 7, 7)           8,640        423,360
       BatchNorm-152                              (1, 960, 7, 7)           3,840              0
           RELU6-153                              (1, 960, 7, 7)               0              0
          Conv2D-154                              (1, 320, 7, 7)         307,200     15,052,800
       BatchNorm-155                              (1, 320, 7, 7)           1,280              0
LinearBottleneck-156                              (1, 320, 7, 7)               0              0
          Conv2D-157                             (1, 1280, 7, 7)         409,600     20,070,400
       BatchNorm-158                             (1, 1280, 7, 7)           5,120              0
           RELU6-159                             (1, 1280, 7, 7)               0              0
 GlobalAvgPool2D-160                             (1, 1280, 1, 1)               0              0
          Conv2D-161                             (1, 1000, 1, 1)       1,280,000      1,280,000
         Flatten-162                                   (1, 1000)               0              0
     MobileNetV2-163                                   (1, 1000)               0              0
===============================================================================================
Parameters in forward computation graph, duplicate included
   Total params: 3,539,136
   Trainable params: 3,504,960
   Non-trainable params: 34,176
   Total MACCs: 313,619,328
Shared params in forward computation graph: 0
Unique parameters in model: 3539136
-----------------------------------------------------------------------------------------------
```

# After - Removing first 1x1 conv in the first bottleneck layer
```
-----------------------------------------------------------------------------------------------
        Layer (type)                                Output Shape         Param #  Multiply-Adds
===============================================================================================
               Input                            (1, 3, 224, 224)               0              0
            Conv2D-1                           (1, 32, 112, 112)             864     10,838,016
         BatchNorm-2                           (1, 32, 112, 112)             128              0
             RELU6-3                           (1, 32, 112, 112)               0              0
            Conv2D-4                           (1, 32, 112, 112)             288      3,612,672
         BatchNorm-5                           (1, 32, 112, 112)             128              0
             RELU6-6                           (1, 32, 112, 112)               0              0
            Conv2D-7                           (1, 16, 112, 112)             512      6,422,528
         BatchNorm-8                           (1, 16, 112, 112)              64              0
  LinearBottleneck-9                           (1, 16, 112, 112)               0              0
           Conv2D-10                           (1, 96, 112, 112)           1,536     19,267,584
        BatchNorm-11                           (1, 96, 112, 112)             384              0
            RELU6-12                           (1, 96, 112, 112)               0              0
           Conv2D-13                             (1, 96, 56, 56)             864      2,709,504
        BatchNorm-14                             (1, 96, 56, 56)             384              0
            RELU6-15                             (1, 96, 56, 56)               0              0
           Conv2D-16                             (1, 24, 56, 56)           2,304      7,225,344
        BatchNorm-17                             (1, 24, 56, 56)              96              0
 LinearBottleneck-18                             (1, 24, 56, 56)               0              0
           Conv2D-19                            (1, 144, 56, 56)           3,456     10,838,016
        BatchNorm-20                            (1, 144, 56, 56)             576              0
            RELU6-21                            (1, 144, 56, 56)               0              0
           Conv2D-22                            (1, 144, 56, 56)           1,296      4,064,256
        BatchNorm-23                            (1, 144, 56, 56)             576              0
            RELU6-24                            (1, 144, 56, 56)               0              0
           Conv2D-25                             (1, 24, 56, 56)           3,456     10,838,016
        BatchNorm-26                             (1, 24, 56, 56)              96              0
 LinearBottleneck-27                             (1, 24, 56, 56)               0              0
           Conv2D-28                            (1, 144, 56, 56)           3,456     10,838,016
        BatchNorm-29                            (1, 144, 56, 56)             576              0
            RELU6-30                            (1, 144, 56, 56)               0              0
           Conv2D-31                            (1, 144, 28, 28)           1,296      1,016,064
        BatchNorm-32                            (1, 144, 28, 28)             576              0
            RELU6-33                            (1, 144, 28, 28)               0              0
           Conv2D-34                             (1, 32, 28, 28)           4,608      3,612,672
        BatchNorm-35                             (1, 32, 28, 28)             128              0
 LinearBottleneck-36                             (1, 32, 28, 28)               0              0
           Conv2D-37                            (1, 192, 28, 28)           6,144      4,816,896
        BatchNorm-38                            (1, 192, 28, 28)             768              0
            RELU6-39                            (1, 192, 28, 28)               0              0
           Conv2D-40                            (1, 192, 28, 28)           1,728      1,354,752
        BatchNorm-41                            (1, 192, 28, 28)             768              0
            RELU6-42                            (1, 192, 28, 28)               0              0
           Conv2D-43                             (1, 32, 28, 28)           6,144      4,816,896
        BatchNorm-44                             (1, 32, 28, 28)             128              0
 LinearBottleneck-45                             (1, 32, 28, 28)               0              0
           Conv2D-46                            (1, 192, 28, 28)           6,144      4,816,896
        BatchNorm-47                            (1, 192, 28, 28)             768              0
            RELU6-48                            (1, 192, 28, 28)               0              0
           Conv2D-49                            (1, 192, 28, 28)           1,728      1,354,752
        BatchNorm-50                            (1, 192, 28, 28)             768              0
            RELU6-51                            (1, 192, 28, 28)               0              0
           Conv2D-52                             (1, 32, 28, 28)           6,144      4,816,896
        BatchNorm-53                             (1, 32, 28, 28)             128              0
 LinearBottleneck-54                             (1, 32, 28, 28)               0              0
           Conv2D-55                            (1, 192, 28, 28)           6,144      4,816,896
        BatchNorm-56                            (1, 192, 28, 28)             768              0
            RELU6-57                            (1, 192, 28, 28)               0              0
           Conv2D-58                            (1, 192, 14, 14)           1,728        338,688
        BatchNorm-59                            (1, 192, 14, 14)             768              0
            RELU6-60                            (1, 192, 14, 14)               0              0
           Conv2D-61                             (1, 64, 14, 14)          12,288      2,408,448
        BatchNorm-62                             (1, 64, 14, 14)             256              0
 LinearBottleneck-63                             (1, 64, 14, 14)               0              0
           Conv2D-64                            (1, 384, 14, 14)          24,576      4,816,896
        BatchNorm-65                            (1, 384, 14, 14)           1,536              0
            RELU6-66                            (1, 384, 14, 14)               0              0
           Conv2D-67                            (1, 384, 14, 14)           3,456        677,376
        BatchNorm-68                            (1, 384, 14, 14)           1,536              0
            RELU6-69                            (1, 384, 14, 14)               0              0
           Conv2D-70                             (1, 64, 14, 14)          24,576      4,816,896
        BatchNorm-71                             (1, 64, 14, 14)             256              0
 LinearBottleneck-72                             (1, 64, 14, 14)               0              0
           Conv2D-73                            (1, 384, 14, 14)          24,576      4,816,896
        BatchNorm-74                            (1, 384, 14, 14)           1,536              0
            RELU6-75                            (1, 384, 14, 14)               0              0
           Conv2D-76                            (1, 384, 14, 14)           3,456        677,376
        BatchNorm-77                            (1, 384, 14, 14)           1,536              0
            RELU6-78                            (1, 384, 14, 14)               0              0
           Conv2D-79                             (1, 64, 14, 14)          24,576      4,816,896
        BatchNorm-80                             (1, 64, 14, 14)             256              0
 LinearBottleneck-81                             (1, 64, 14, 14)               0              0
           Conv2D-82                            (1, 384, 14, 14)          24,576      4,816,896
        BatchNorm-83                            (1, 384, 14, 14)           1,536              0
            RELU6-84                            (1, 384, 14, 14)               0              0
           Conv2D-85                            (1, 384, 14, 14)           3,456        677,376
        BatchNorm-86                            (1, 384, 14, 14)           1,536              0
            RELU6-87                            (1, 384, 14, 14)               0              0
           Conv2D-88                             (1, 64, 14, 14)          24,576      4,816,896
        BatchNorm-89                             (1, 64, 14, 14)             256              0
 LinearBottleneck-90                             (1, 64, 14, 14)               0              0
           Conv2D-91                            (1, 384, 14, 14)          24,576      4,816,896
        BatchNorm-92                            (1, 384, 14, 14)           1,536              0
            RELU6-93                            (1, 384, 14, 14)               0              0
           Conv2D-94                            (1, 384, 14, 14)           3,456        677,376
        BatchNorm-95                            (1, 384, 14, 14)           1,536              0
            RELU6-96                            (1, 384, 14, 14)               0              0
           Conv2D-97                             (1, 96, 14, 14)          36,864      7,225,344
        BatchNorm-98                             (1, 96, 14, 14)             384              0
 LinearBottleneck-99                             (1, 96, 14, 14)               0              0
          Conv2D-100                            (1, 576, 14, 14)          55,296     10,838,016
       BatchNorm-101                            (1, 576, 14, 14)           2,304              0
           RELU6-102                            (1, 576, 14, 14)               0              0
          Conv2D-103                            (1, 576, 14, 14)           5,184      1,016,064
       BatchNorm-104                            (1, 576, 14, 14)           2,304              0
           RELU6-105                            (1, 576, 14, 14)               0              0
          Conv2D-106                             (1, 96, 14, 14)          55,296     10,838,016
       BatchNorm-107                             (1, 96, 14, 14)             384              0
LinearBottleneck-108                             (1, 96, 14, 14)               0              0
          Conv2D-109                            (1, 576, 14, 14)          55,296     10,838,016
       BatchNorm-110                            (1, 576, 14, 14)           2,304              0
           RELU6-111                            (1, 576, 14, 14)               0              0
          Conv2D-112                            (1, 576, 14, 14)           5,184      1,016,064
       BatchNorm-113                            (1, 576, 14, 14)           2,304              0
           RELU6-114                            (1, 576, 14, 14)               0              0
          Conv2D-115                             (1, 96, 14, 14)          55,296     10,838,016
       BatchNorm-116                             (1, 96, 14, 14)             384              0
LinearBottleneck-117                             (1, 96, 14, 14)               0              0
          Conv2D-118                            (1, 576, 14, 14)          55,296     10,838,016
       BatchNorm-119                            (1, 576, 14, 14)           2,304              0
           RELU6-120                            (1, 576, 14, 14)               0              0
          Conv2D-121                              (1, 576, 7, 7)           5,184        254,016
       BatchNorm-122                              (1, 576, 7, 7)           2,304              0
           RELU6-123                              (1, 576, 7, 7)               0              0
          Conv2D-124                              (1, 160, 7, 7)          92,160      4,515,840
       BatchNorm-125                              (1, 160, 7, 7)             640              0
LinearBottleneck-126                              (1, 160, 7, 7)               0              0
          Conv2D-127                              (1, 960, 7, 7)         153,600      7,526,400
       BatchNorm-128                              (1, 960, 7, 7)           3,840              0
           RELU6-129                              (1, 960, 7, 7)               0              0
          Conv2D-130                              (1, 960, 7, 7)           8,640        423,360
       BatchNorm-131                              (1, 960, 7, 7)           3,840              0
           RELU6-132                              (1, 960, 7, 7)               0              0
          Conv2D-133                              (1, 160, 7, 7)         153,600      7,526,400
       BatchNorm-134                              (1, 160, 7, 7)             640              0
LinearBottleneck-135                              (1, 160, 7, 7)               0              0
          Conv2D-136                              (1, 960, 7, 7)         153,600      7,526,400
       BatchNorm-137                              (1, 960, 7, 7)           3,840              0
           RELU6-138                              (1, 960, 7, 7)               0              0
          Conv2D-139                              (1, 960, 7, 7)           8,640        423,360
       BatchNorm-140                              (1, 960, 7, 7)           3,840              0
           RELU6-141                              (1, 960, 7, 7)               0              0
          Conv2D-142                              (1, 160, 7, 7)         153,600      7,526,400
       BatchNorm-143                              (1, 160, 7, 7)             640              0
LinearBottleneck-144                              (1, 160, 7, 7)               0              0
          Conv2D-145                              (1, 960, 7, 7)         153,600      7,526,400
       BatchNorm-146                              (1, 960, 7, 7)           3,840              0
           RELU6-147                              (1, 960, 7, 7)               0              0
          Conv2D-148                              (1, 960, 7, 7)           8,640        423,360
       BatchNorm-149                              (1, 960, 7, 7)           3,840              0
           RELU6-150                              (1, 960, 7, 7)               0              0
          Conv2D-151                              (1, 320, 7, 7)         307,200     15,052,800
       BatchNorm-152                              (1, 320, 7, 7)           1,280              0
LinearBottleneck-153                              (1, 320, 7, 7)               0              0
          Conv2D-154                             (1, 1280, 7, 7)         409,600     20,070,400
       BatchNorm-155                             (1, 1280, 7, 7)           5,120              0
           RELU6-156                             (1, 1280, 7, 7)               0              0
 GlobalAvgPool2D-157                             (1, 1280, 1, 1)               0              0
          Conv2D-158                             (1, 1000, 1, 1)       1,280,000      1,280,000
         Flatten-159                                   (1, 1000)               0              0
     MobileNetV2-160                                   (1, 1000)               0              0
===============================================================================================
Parameters in forward computation graph, duplicate included
   Total params: 3,537,984
   Trainable params: 3,503,872
   Non-trainable params: 34,112
   Total MACCs: 300,774,272
Shared params in forward computation graph: 0
Unique parameters in model: 3537984
-----------------------------------------------------------------------------------------------
```

**Comment by Jerryzcn** [comment]
We will probably train a new model for this.

**Comment by hetong007** [comment]
Thank you for this contribution! We have re-trained the MobileNet v2, please apply the following diff to your PR to make it effective:

```
diff --git a/docs/model_zoo/classification.rst b/docs/model_zoo/classification.rst
index 84ca701..ddaf242 100644
--- a/docs/model_zoo/classification.rst
+++ b/docs/model_zoo/classification.rst
@@ -205,13 +205,13 @@ MobileNet
    +--------------------------+--------+--------+----------+-----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
    | MobileNet0.25 [4]_       | 52.91  | 76.94  | f0046a3d | `shell script <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenet0.25.sh>`_          | `log <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenet0.25.log>`_        |
    +--------------------------+--------+--------+----------+-----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
-   | MobileNetV2_1.0 [5]_     | 71.92  | 90.56  | 36da4ff1 | `shell script <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_1.0.sh>`_        | `log <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_1.0.log>`_      |
+   | MobileNetV2_1.0 [5]_     | 72.04  | 90.57  | f9952bcd | `shell script <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_1.0.sh>`_        | `log <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_1.0.log>`_      |
    +--------------------------+--------+--------+----------+-----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
-   | MobileNetV2_0.75 [5]_    | 69.61  | 88.95  | e2be7b72 | `shell script <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_0.75.sh>`_       | `log <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_0.75.log>`_     |
+   | MobileNetV2_0.75 [5]_    | 69.36  | 88.50  | b56e3d1c | `shell script <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_0.75.sh>`_       | `log <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_0.75.log>`_     |
    +--------------------------+--------+--------+----------+-----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
-   | MobileNetV2_0.5 [5]_     | 64.49  | 85.47  | aabd26cd | `shell script <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_0.5.sh>`_        | `log <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_0.5.log>`_      |
+   | MobileNetV2_0.5 [5]_     | 64.43  | 85.31  | 08038185 | `shell script <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_0.5.sh>`_        | `log <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_0.5.log>`_      |
    +--------------------------+--------+--------+----------+-----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
-   | MobileNetV2_0.25 [5]_    | 50.74  | 74.56  | ae8f9392 | `shell script <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_0.25.sh>`_       | `log <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_0.25.log>`_     |
+   | MobileNetV2_0.25 [5]_    | 51.76  | 74.89  | 9b1d2cc3 | `shell script <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_0.25.sh>`_       | `log <https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenetv2_0.25.log>`_     |
    +--------------------------+--------+--------+----------+-----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+

 VGG
diff --git a/gluoncv/model_zoo/model_store.py b/gluoncv/model_zoo/model_store.py
index 881fa6e..88906e4 100644
--- a/gluoncv/model_zoo/model_store.py
+++ b/gluoncv/model_zoo/model_store.py
@@ -18,10 +18,10 @@ _model_sha1 = {name: checksum for checksum, name in [
     ('0130d2aa2f7e3a63db35579b243e25f512172371', 'mobilenet0.5'),
     ('84c801e27b1ac5040b6e945c0d1f8d49e9a59f3d', 'mobilenet0.75'),
     ('efbb2ca3881998d5a8c5cb6c457a28c1e085fed5', 'mobilenet1.0'),
-    ('36da4ff1867abccd32b29592d79fc753bca5a215', 'mobilenetv2_1.0'),
-    ('e2be7b72a79fe4a750d1dd415afedf01c3ea818d', 'mobilenetv2_0.75'),
-    ('aabd26cd335379fcb72ae6c8fac45a70eab11785', 'mobilenetv2_0.5'),
-    ('ae8f9392789b04822cbb1d98c27283fc5f8aa0a7', 'mobilenetv2_0.25'),
+    ('f9952bcde7a7982947ac5240546e1c1c8f057370', 'mobilenetv2_1.0'),
+    ('b56e3d1c33eb52d0b90678db4ce6c5ca6c9a6704', 'mobilenetv2_0.75'),
+    ('0803818513599fa1329524ee3607b708b4a4630f', 'mobilenetv2_0.5'),
+    ('9b1d2cc38fed4cd171a7f7a0d17fe1a905573887', 'mobilenetv2_0.25'),
     ('a0666292f0a30ff61f857b0b66efc0228eb6a54b', 'resnet18_v1'),
     ('48216ba99a8b1005d75c0f3a0c422301a0473233', 'resnet34_v1'),
     ('cc729d95031ca98cf2ff362eb57dee4d9994e4b2', 'resnet50_v1'),
```

**Comment by mightydeveloper** [comment]
Sure! I'll apply the diff

**Comment by hetong007** [comment]
Would you please re-trigger the CI by `git commit --allow-empty -m "Trigger CI"`? Our CI server has issues when it downloads new params for the first time.

**Comment by mli** [comment]
Job PR-773-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-773/3/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
