### PR TITLE
Hybrid FCN + FCN for ADE20K

### PR DESCRIPTION
**Pull request by zhanghang1989**

### CODE REVIEW

**Comment by mli** [comment]
Job PR-152-6 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-152/6/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-152-7 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-152/7/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhanghang1989** [comment]
address comment 5. https://github.com/dmlc/gluon-cv/issues/150

**Comment by mli** [comment]
Job PR-152-8 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-152/8/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-152-9 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-152/9/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
