### PR TITLE
set ctx to cpu if args.gpus=0

### PR DESCRIPTION
**Pull request by kangks**
ctx should be mx.cpu() when args.gpus=0 and not mx.gpu(0)

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1417-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1417/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1417-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1417/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
@kangks Hi, here args.gpus expect a comma separated string in command line, e.g. `python train_xxx.py --gpus 0,1,2,3`
So `python xxx --gpus 0` will use the first gpu, `python xxx --gpus ''` will use cpu.

**Comment by mli** [comment]
Job PR-1417-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1417/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
Closing temporarily, let me know if you have more questions/suggestions on this.

**Pull request closed without merging**
