### PR TITLE
Proposal of YOLOv3 Custom Training API

### PR DESCRIPTION
**Pull request by ivanquirino**
This is a proposal of a custom training API for YOLOv3 for making it easier to train YOLOv3 for custom data sets/tasks. Recently I had to train a custom data set and I had to adapt the current train_yolo.py script, so I would like to contribute a nice API so that everyone can train custom data sets easier. I would like to know what of you think of such API and if this contribution would be accepted.

I would love suggestions and criticism to make it better. Of course, I also think of doing a yolo_custom_train.py script that uses this class to give users a command line tool to make it even easier.

I'm a new user of MXNet and GluonCV and I may be doing something dumb, but I'm doing this because I really liked this project, the great docs and examples, and the big model zoo offered. ^^

### CODE REVIEW

**Comment by zhreshold** [comment]
While I REALLY like the your idea to encapsulate a more user friendly API for training custom data, the proposal needs to be polished. 

And as you have noticed that there are tons of hyper-parameters to take care. We might need a better way to avoid laborious maintenance job since there are way more algorithms than YOLO itself.

**Comment by ivanquirino** [comment]
I see, what you are talking about a base custom training API, that can be extended to other algorithms? I initially thinked of YOLOv3 because that's my use case. When thinking on the terms of the whole project what you're saying totally makes sense. I would be happy to take input and suggestions on how to start this, how to best contribute to this. 

Let's say we have:
```python
class BaseCustomTraining

class BaseCustomClassificationTraining

class BaseCustomDetectionTraining

class YOLOV3CustomTraining
```

Would that be something reasonable to work with? I would start myself with `BaseCustomTraining`, `BaseCustomDetectionTraining` and `YOLOV3CustomTraining`.

I would like to make GluonCV the most application friendly as possible, because I found in MXNet and GluonCV the most deployment ready and application ready framework when I needed, with all the documentation needed to put deep learning at production.

**Comment by zhreshold** [comment]
Sorry for late reply, these can be complimentary training helpers, and I guess it can be fit in `gluoncv.contrib.train' module

**Comment by zhreshold** [comment]
There will be an unified fit interface for all detection models, I am closing the discussion here

**Pull request closed without merging**
