### PR TITLE
Fix typo in MultiEvalModel

### PR DESCRIPTION
**Pull request by jianchao-li**
Hello, @zhanghang1989. Could you please take a look at this PR and merge it if it looks good to you? If anything is needed from my side, please kindly tell me.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-337-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-337/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-337-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-337/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-337-6 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-337/6/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-337-7 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-337/7/index.html 
Code coverage of this PR:  vs. Master:

**Comment by jianchao-li** [comment]
Closed this PR since it has become a bit messy.

**Pull request closed without merging**
