### PR TITLE
"fix the update input is a list bug of VOCMApMetric"

### PR DESCRIPTION
**Pull request by Wondersui**
If the update input is a list of batch,the VOC evaluation will get different mAP by different batch_size,because the length of gt_difficult is not same with len(list)*batch_size.

### CODE REVIEW

**Comment by zhreshold** [comment]
can you resolve the conflict first?

**Comment by mli** [comment]
Job PR-723-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-723/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
well, I have concerns to allow gt_labels be a list, will this also affact in case predictions are list or pure ndarrays?

**Comment by Wondersui** [comment]
> well, I have concerns to allow gt_labels be a list, will this also affact in case predictions are list or pure ndarrays?

If the gt_labels is a list,the other inputs of the update should be a list,just like the script of gluon-cv/scripts/detection/yolo/train_yolo3.py:
`
def validate(net, val_data, ctx, eval_metric):
    """Test on validation dataset."""
    eval_metric.reset()
    # set nms threshold and topk constraint
    net.set_nms(nms_thresh=0.45, nms_topk=400)
    mx.nd.waitall()
    net.hybridize()
    for batch in val_data:
        data = gluon.utils.split_and_load(batch[0], ctx_list=ctx, batch_axis=0, even_split=False)
        label = gluon.utils.split_and_load(batch[1], ctx_list=ctx, batch_axis=0, even_split=False)
        det_bboxes = []
        det_ids = []
        det_scores = []
        gt_bboxes = []
        gt_ids = []
        gt_difficults = []
        for x, y in zip(data, label):
            # get prediction results
            ids, scores, bboxes = net(x)
            det_ids.append(ids)
            det_scores.append(scores)
            # clip to image size
            det_bboxes.append(bboxes.clip(0, batch[0].shape[2]))
            # split ground truths
            gt_ids.append(y.slice_axis(axis=-1, begin=4, end=5))
            gt_bboxes.append(y.slice_axis(axis=-1, begin=0, end=4))
            gt_difficults.append(y.slice_axis(axis=-1, begin=5, end=6) if y.shape[-1] > 5 else None)

        # update metric
        eval_metric.update(det_bboxes, det_ids, det_scores, gt_bboxes, gt_ids, gt_difficults)
    return eval_metric.get()
`
But if you use this script and don't change the code of VOCMApMetric, the VOC evaluation will get different mAP by different batch_size.

**Comment by zhreshold** [comment]
"But if you use this script and don't change the code of VOCMApMetric, the VOC evaluation will get different mAP by different batch_size." I don't get it, I tried different batch size and got exactly same results? Did I miss something?

**Comment by mli** [comment]
Job PR-723-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-723/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by Wondersui** [comment]
> "But if you use this script and don't change the code of VOCMApMetric, the VOC evaluation will get different mAP by different batch_size." I don't get it, I tried different batch size and got exactly same results? Did I miss something?

Maybe the reason is I used my own dataset and  VOCMApMetric, the input of gt_difficults is a list of None.

**Comment by mli** [comment]
Job PR-723-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-723/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
@Wondersui Yep, that could be the problem. This is merged now, thanks for the contribution!!

**Pull request merged**
