### PR TITLE
resnetv1b.py for MXNet-master

### PR DESCRIPTION
**Pull request by jinboci**
`resnetv1b` for MXNet-master based on the changes of `nn.gn`
Passed tests for `resnetv1b.py` at `test_imagenet_models()` in `test_model_zoo.py` on my local sever.

Changes due to mxnet-master's different implementations from 1.7:
- `nn.HybridSequential` on mxnet-master does not accept the parameter `prefix`
- No `name_scope` defined in class `HybridSequential` `HybridBlock` `Block` on mxnet-master (block.py)

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1504-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1504/2/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1504-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1504/3/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
lint fails

**Comment by mli** [comment]
Job PR-1504-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1504/4/index.html 
Code coverage of this PR:  vs. Master:

**Comment by jinboci** [comment]
Changes have already been merged

**Pull request closed without merging**
