### PR TITLE
Allow segmentation to work with image sizes other than 480 X 480.

### PR DESCRIPTION
**Pull request by ragavvenkatesan**
Error:
-----

Error can be simulated by passing a `height = 240`, `width=240` in `scripts\segmentation\train.py`. `**kwargs` are not passed along and dropped. This means that using `height`, `width` in `get_segmentation_model` results in the following error: 

```bash
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    trainer = Trainer(args)
  File "train.py", line 126, in __init__
    aux=args.aux, norm_kwargs=args.norm_kwargs)
  File "/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluoncv-0.3.0-py3.6.egg/gluoncv/model_zoo/segbase.py", line 23, in get_segmentation_model
  File "/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluoncv-0.3.0-py3.6.egg/gluoncv/model_zoo/fcn.py", line 131, in get_fcn
  File "/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluoncv-0.3.0-py3.6.egg/gluoncv/model_zoo/fcn.py", line 45, in __init__
TypeError: __init__() got an unexpected keyword argument 'height'
``` 

Similar problem was also encountered in `DataLoader`.

PR Notes:
----------
I am simply making sure that `**kwargs` are handed over to classes like `_FCNHead`.

Testing:
--------
I verified by running the following scripts on a machine with 4 volta GPUs using the modified `scripts\segmentation\train.py` file.

```bash
python scripts/segmentation/train.py --ngpus 4 --dataset pascal_voc --crop-size 120 --model fcn --epochs 2
python scripts/segmentation/train.py --ngpus 4 --dataset pascal_voc --crop-size 120 --model psp --epochs 2
python scripts/segmentation/train.py --ngpus 4 --dataset pascal_voc --crop-size 120 --model deeplab --epochs 2
python scripts/segmentation/train.py --ngpus 4 --dataset pascal_aug --crop-size 120 --model deeplab --epochs 2
python scripts/segmentation/train.py --ngpus 4 --dataset ade20k --crop-size 240 --model fcn --epochs 2
python scripts/segmentation/train.py --ngpus 4 --dataset coco --crop-size 240 --model fcn --epochs 2
```

### CODE REVIEW

**Comment by zhanghang1989** [comment]
Thanks for the feedback and contribution! I have a local change related to this issue and will add a PR including this fix and other updates.

**Comment by ragavvenkatesan** [comment]
Thanks.
Please let me know if you have any ETA on the merge.

**Comment by zhanghang1989** [comment]
We are adding the fix together with cityscapes dataset, which requires a large crop size. The estimated time is about a week.

**Comment by ragavvenkatesan** [comment]
That seems too long. Is there anyway that you can merge this now and add the commit the extra code as they come along ?

**Comment by zhanghang1989** [comment]
Sure. I will make a PR providing the dataset only without pre-trained models. I will do that later today.

**Comment by zhanghang1989** [comment]
Closing this in favor of PR https://github.com/dmlc/gluon-cv/pull/322

**Pull request closed without merging**
