### PR TITLE
lazy import cv2

### PR DESCRIPTION
**Pull request by zhreshold**
Fix cv2 import, please always use lazy import otherwise import gluoncv will fail on envs that do not have opencv

@bryanyzhu @FrankYoungchen

### CODE REVIEW

**Comment by bryanyzhu** [comment]
Got it, @FrankYoungchen mentioned to me before that using this inside the class definition will cause error during multiprocess testing. So we move it outside. Let me confirm with him to see if there are any alternatives.

**Comment by mli** [comment]
Job PR-1158-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1158/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
I see, there might be race condition if multiple process want to install cv2. Let me figure out how to add a lock

**Comment by bryanyzhu** [comment]
@zhreshold Sounds good, thank you. 

For now, if this breaks others' import of gluoncv, you can merge the PR first. We will figure out a solution for tracking later.

**Comment by mli** [comment]
Job PR-1158-3 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1158/3/index.html 
Code coverage of this PR:  vs. Master:

**Pull request merged**
