### PR TITLE
Revise danet.py

### PR DESCRIPTION
**Pull request by BebDong**
The dropout layer should be placed before the classification layer.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1507-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1507/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by BebDong** [comment]
See official repository https://github.com/junfu1115/DANet/blob/master/encoding/models/sseg/danet.py#L79

**Comment by bryanyzhu** [comment]
@xdeng7 Could you please review this PR? Thank you.

**Comment by xdeng7** [comment]
> @xdeng7 Could you please review this PR? Thank you.

Adding dropout is a new feature in the original repo. All looks good.

**Review by bryanyzhu — APPROVED** [review]
Thank you for the PR. Will merge it.

**Pull request merged**
