### PR TITLE
Monodepth2 tutorials

### PR DESCRIPTION
**Pull request by KuangHaofei**
This PR update the monodepth2 training tutorials and adding posenet tutorials.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1435-1 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1435/1/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1435-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1435/4/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1435-5 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1435/5/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1435-6 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1435/6/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1435-7 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1435/7/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1435-8 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1435/8/index.html 
Code coverage of this PR:  vs. Master:

**Comment by mli** [comment]
Job PR-1435-9 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-1435/9/index.html 
Code coverage of this PR:  vs. Master:

**Review by bryanyzhu — APPROVED** [review]
Looks good to me, thank you for the awesome contribution!

**Pull request merged**
