### PR TITLE
Force unittest and coverage

### PR DESCRIPTION
**Pull request by zhreshold**
- force unittest check
- add coverage and badge

### CODE REVIEW

**Comment by mli** [comment]
Job PR-111-2 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/2/index.html 
Code coverage of this PR: [pr.svg](http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/2/coverage.svg) vs. Master: [master.svg](s3://gluon-cv.mxnet.io/coverage.svg)

**Comment by mli** [comment]
Job PR-111-4 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/4/index.html 
Code coverage of this PR: [pr.svg](http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/4/coverage.svg) vs. Master: [master.svg](s3://gluon-cv.mxnet.io/coverage.svg)

**Comment by mli** [comment]
Job PR-111-6 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/6/index.html 
Code coverage of this PR: [pr.svg](http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/6/coverage.svg) vs. Master: [master.svg](s3://gluon-cv.mxnet.io/coverage.svg)

**Comment by mli** [comment]
Job PR-111-23 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/23/index.html 
Code coverage of this PR: [pr.svg](http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/23/coverage.svg) vs. Master: [master.svg](s3://gluon-cv.mxnet.io/coverage.svg)

**Comment by mli** [comment]
Job PR-111-36 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/36/index.html 
Code coverage of this PR: [pr.svg](http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/36/coverage.svg) vs. Master: [master.svg](http://gluon-cv.mxnet.io/coverage.svg)

**Comment by mli** [comment]
Job PR-111-37 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/37/index.html 
Code coverage of this PR: [pr.svg](http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/37/coverage.svg) vs. Master: [master.svg](http://gluon-cv.mxnet.io/coverage.svg)

**Comment by mli** [comment]
Job PR-111-38 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/38/index.html 
Code coverage of this PR: [pr.svg](http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/38/coverage.svg) vs. Master: [master.svg](http://gluon-cv.mxnet.io/coverage.svg)

**Comment by mli** [comment]
Job PR-111-39 is done. 
Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-111/39/index.html 
Code coverage of this PR:  vs. Master:

**Comment by zhreshold** [comment]
@hetong007 @zhanghang1989 
I am going to merge this, be prepared that you will need to make sure PRs in the future must pass unittest. 
And we need to continuously achieving better code coverage.

**Pull request merged**
